apiVersion: apps/v1
kind: Deployment
metadata:
  name: skys-api-app-dep
spec:
  selector:
    matchLabels:
      app: skys-api-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: skys-api-app-pod
      labels:
        app: skys-api-app
    spec:
      containers:
        - name: skys-api-app
          image: skys-api:nestjs
          imagePullPolicy: Never
          volumeMounts:
            - name: skys-api-app
              mountPath: /var/www
            - name: skys-api-npm-log
              mountPath: /root/.npm/_logs
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: PRISMA_DATABASE_URL
              value: "mysql://root:password@skys-api-db-svc:3306/skys-api"
            - name: DATABASE_HOST
              value: "skys-api-db-svc"
            - name: DATABASE_PORT
              value: "3306"
      volumes:
        - name: skys-api-app
          hostPath:
            path: {{ .Values.container.volume.project_root_path }}
            type: DirectoryOrCreate
        - name: skys-api-npm-log
          hostPath:
            path: {{ .Values.container.volume.project_root_path }}/logs/npm
            type: DirectoryOrCreate