apiVersion: apps/v1
kind: Deployment
metadata:
  name: skys-scraper-app-dep
spec:
  selector:
    matchLabels:
      app: skys-scraper-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: skys-scraper-app-pod
      labels:
        app: skys-scraper-app
    spec:
      containers:
        - name: skys-scraper-app
          image: skys-scraper:puppeteer-with-nestjs
          imagePullPolicy: Never
          volumeMounts:
            - name: skys-scraper-app
              mountPath: /var/www
            - name: skys-scraper-app-npm-log
              mountPath: /root/.npm/_logs
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: PRISMA_DATABASE_URL
              value: "mysql://root:password@skys-scraper-db-svc:3306/skys-scraper"
            - name: DATABASE_HOST
              value: "skys-scraper-db-svc"
            - name: DATABASE_PORT
              value: "3306"
            - name: PM2_PUBLIC_KEY
              value: {{ .Values.container.pm2io.public_key }}
            - name: PM2_SECRET_KEY
              value: {{ .Values.container.pm2io.secret_key }}
      volumes:
        - name: skys-scraper-app
          hostPath:
            path: {{ .Values.container.volume.project_root_path }}
            type: DirectoryOrCreate
        - name: skys-scraper-app-npm-log
          hostPath:
            path: {{ .Values.container.volume.project_root_path }}/logs/npm
            type: DirectoryOrCreate