apiVersion: apps/v1
kind: Deployment
metadata:
  name: skys-client-app-dep
spec:
  selector:
    matchLabels:
      app: skys-client-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: skys-client-app-pod
      labels:
        app: skys-client-app
    spec:
      containers:
        - name: skys-client-app
          image: skys-client:nextjs
          imagePullPolicy: Never
          volumeMounts:
            - name: skys-client-app
              mountPath: /var/www
            - name: skys-client-npm-log
              mountPath: /root/.npm/_logs
          ports:
            - containerPort: 3000
          env:
            - name: CHOKIDAR_USEPOLLING
              value: "true" # コンテナ内でホットリロードを有効にする
            - name: NODE_ENV
              value: "development"
            - name: NEXT_PUBLIC_LOCAL_API_BASE_URL
              value: "http://localhost:3000/v1/"
      volumes:
        - name: skys-client-app
          hostPath:
            path: {{ .Values.container.volume.project_root_path }}
            type: DirectoryOrCreate
        - name: skys-client-npm-log
          hostPath:
            path: {{ .Values.container.volume.project_root_path }}/logs/npm
            type: DirectoryOrCreate