apiVersion: v1
kind: Pod
metadata:
  name: skys-scraper-app-pod
  labels:
    app: skys-scraper-app
spec:
  containers:
    - name: skys-scraper-app
      image: skys-scraper:puppeteer-with-nestjs
      imagePullPolicy: Never
      volumeMounts:
        - name: skys-scraper-app
          mountPath: /var/www
        - name: skys-scraper-app-npm-log
          mountPath: /root/.npm/_logs
      ports:
        - containerPort: 3000
  volumes:
    - name: skys-scraper-app
      hostPath:
        path: /Users/hiroki/Project/skys-scraper
        type: DirectoryOrCreate
    - name: skys-scraper-app-npm-log
      hostPath:
        path: /Users/hiroki/Project/skys-scraper/logs/npm
        type: DirectoryOrCreate
