service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30001

container:
  volume:
    project_root_path: default
  ports:
    containerPort: 3000
  pm2io:
    public_key: default
    secret_key: default