apiVersion: apps/v1
kind: Deployment
metadata:
  name: skys-scraper-db-dep
spec:
  selector:
    matchLabels:
      app: skys-scraper-db
  strategy:
    type: Recreate
  template:
    metadata:
      name: skys-scraper-db-pod
      labels:
        app: skys-scraper-db
    spec:
      containers:
        - name: skys-scraper-db
          image: skys-scraper:mysql8.0
          imagePullPolicy: Never
          volumeMounts:
            - name: skys-scraper-mysql-init
              mountPath: /docker-entrypoint-initdb.d
            - name: skys-scraper-mysql-conf
              mountPath: /etc/mysql/conf.d
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: TZ
              value: Asia/Tokyo
          ports:
            - containerPort: 3306
      volumes:
        - name: skys-scraper-mysql-init
          configMap:
            name: skys-scraper-db-init
            items:
              - key: initdb.sql
                path: initdb.sql
        - name: skys-scraper-mysql-conf
          configMap:
            name: skys-scraper-db-conf
            items:
              - key: my.cnf
                path: my.cnf
